apiVersion: v1
kind: Service
metadata:
  name: nodernetes
  namespace: eks-noder
  labels:
    app: noder
spec:
  selector:
    app: noder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80