apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodernetes
  namespace: eks-noder
  labels:
    app: noder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: noder
  template:
    metadata:
      labels:
        app: noder
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: noder
        image: nielsenjared/noder:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux